config/routes.rb
Rails.application.routes.draw do
  resources :items

  root 'items#index'

  get 'active' => 'items#active'
  get 'completed' => 'items#completed'

end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController


	def index
		@items = Item.new
		@all_items = Item.all
		@itemCount = Item.count
	end

	def create
		@item = Item.create(item_params)
		redirect_to root_url
	end

	def update
	  @item = Item.find(params[:id])
	  @item.update(item_params)
	 	redirect_to root_url
	end

	def edit
		@item = Item.find(params[:id])
	end

	def destroy
		@item = Item.find(params[:id])
		@item.destroy
		redirect_to root_url
	end

	def active
		@all_active = Item.where(complete: false || nil)
	end

	def completed
		@all_completed = Item.where(complete: true)
	end

	private
	def item_params
		params.require(:item).permit(:description, :complete)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/active.html.erb
<% @all_active.each do |item| %>
	<li <%= 'class=completed' if item.complete? %>>
		<div class="view">	
	
			<%= form_for item do |f| %>
				<%= f.check_box :complete, {:class => "toggle"} %>
				<%= f.submit "Complete?" %>
			<% end %>
	
			<label><%= item.description %></label>

			<%= link_to 'Edit Task', edit_item_path(item), method: :get %>
			<%= link_to 'Delete Task', item,
		     method: :delete,
		     data: { confirm: 'Are you sure?' } %>
			<br><br>

		</div>	
	</li>
<% end %>

app/views/items/completed.html.erb
<% @all_completed.each do |item| %>
	<li <%= 'class=completed' if item.complete? %>>
		<div class="view">	
	
			<%= form_for item do |f| %>
				<%= f.check_box :complete, {:class => "toggle"} %>
				<%= f.submit "Complete?" %>
			<% end %>
	
			<label><%= item.description %></label>

			<%= link_to 'Edit Task', edit_item_path(item), method: :get %>
			<%= link_to 'Delete Task', item,
		     method: :delete,
		     data: { confirm: 'Are you sure?' } %>
			<br><br>

		</div>	
	</li>
<% end %>

app/views/items/edit.html.erb
<h2>Edit Task</h2>
 
<%= form_for @item do |f| %>
  <p>
    <%= f.label "Task" %><br>
    <%= f.text_field :description %>
  </p>
  <p>
  	<%= f.label "Complete?" %><br>
  	<%= f.check_box :complete %>
  </p>
  <p>
    <%= f.submit "Save"%>
  </p>
<% end %>
 
<%= link_to 'Back', root_path %>

app/views/items/index.html.erb
<% @all_items.each do |item| %>
	<li <%= 'class=completed' if item.complete? %>>
		<div class="view">	
	
			<%= form_for item do |f| %>
				<%= f.check_box :complete, {:class => "toggle"} %>
				<%= f.submit "Complete?" %>
			<% end %>
	
			<label><%= item.description %></label>

			<%= link_to 'Edit Task', edit_item_path(item), method: :get %>
			<%= link_to 'Delete Task', item,
		     method: :delete,
		     data: { confirm: 'Are you sure?' } %>
			<br><br>

		</div>	
	</li>
<% end %>

	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<section id="todoapp">
		<header id="header">
			
			<h1>todos</h1>
			
			<%= form_for Item.new do |f| %>
				<%= f.text_field :description, placeholder: "What needs to be done?", id:"new-todo", autofocus: true %>
				<%= f.submit "Add Task", id:"create-button" %>
			
			<% end %>
		</header>

		<section id="main">

		  <!--
			<input id="toggle-all" type="checkbox">
				<label for="toggle-all">Mark all as complete</label>
			-->

			<ul id="todo-list">

				<%= yield %>

			</ul>

	</section>

	<% if Item.count == 0 %>

		<% else %>

			<footer id="footer">

				<span id="todo-count">
					<strong><%= Item.where(complete: false || nil).count %></strong> 
					<% if Item.where(complete: false || nil).count == 1 %>
						item
					<% else %>
						items
					<% end %>
					left 
				</span>

				<ul id="filters">
					<li>
						<%= link_to "All", root_path %>
					</li>
					<li>
						<%= link_to "Active", active_path %>
					</li>
					<li>
						<%= link_to "Completed", completed_path %>
					</li>
				</ul>

				<button id="clear-completed"></button>
			</footer>

		<% end %>

	</section>


<footer id="info">
	<p>Created by J. Spencer Hopkins</p>
	<p>Copyright &copy; <%= Date.today.year %></p>
</footer>

</body>
</html>